import { ShieldAlert } from 'lucide-react'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { EmptyState } from '@/components/layout/EmptyState'
import { SectionTitle } from '@/components/layout/SectionTitle'
import { WorkflowLoadingPanel } from '@/components/workflow/WorkflowLoadingPanel'
import type { WorkflowGroup } from '@/constants/options'
import { WorkflowPanel } from '@/components/workflow/WorkflowPanel'
import { RiskPanel } from './RiskPanel'
import { SupportPanel } from './SupportPanel'
import type { DataPreview, GbifQuery, TriageResult, WorkflowPackage } from '@/lib/types'

// "Support verdict and exports" — visually one card, semantically two
// sub-sections that come from two different endpoints.
//
//   ┌─ Support verdict and exports ───────────────────────────────┐
//   │   Support verdict                                           │  ← /api/study-plan
//   │   SupportPanel (headline + 5 categorical buckets)           │
//   │   RiskPanel (BLOCKING/HIGH/MODERATE/LOW risks)              │
//   │   ──────────────────────────────────────────────────────    │
//   │   Exports                                                   │  ← /api/workflow
//   │   WorkflowLoadingPanel (spinner + skeleton) OR WorkflowPanel│
//   └─────────────────────────────────────────────────────────────┘
//
// The split is invisible from the user's point of view — same single
// card, same outer padding, same border, same scroll behavior. Only
// the loading state inside the Exports section exposes the split:
// the Support verdict fills in immediately, then a divider + spinner
// + skeleton appears in the Exports section until /api/workflow lands.
//
// Why this matters:
//   - Support verdict's headline is generated by the triage LLM call.
//   - Exports' markdown report echoes the same headline so the two
//     sub-sections read as one coherent narrative, not two independent
//     ones.
//   - The triage JSON is forwarded to /api/workflow as `triage` in
//     the request body, so the workflow LLM call literally builds on
//     the verdict instead of inventing a parallel one.
export function TriageSection({
  triage,
  preview,
  workflow,
  workflowError,
  query,
  activeWorkflowGroup,
  setActiveWorkflowGroup,
  activeCodeLanguage,
  setActiveCodeLanguage,
  activeWriteupTab,
  setActiveWriteupTab,
  activeQueryTab,
  setActiveQueryTab,
}: {
  triage: TriageResult | null
  preview: DataPreview | null
  workflow: WorkflowPackage | null
  workflowError?: string
  query: GbifQuery | null
  activeWorkflowGroup: WorkflowGroup
  setActiveWorkflowGroup: (group: WorkflowGroup) => void
  activeCodeLanguage: 'r' | 'python'
  setActiveCodeLanguage: (language: 'r' | 'python') => void
  activeWriteupTab: 'methods' | 'citation' | 'limitations'
  setActiveWriteupTab: (tab: 'methods' | 'citation' | 'limitations') => void
  activeQueryTab: 'sql' | 'predicate'
  setActiveQueryTab: (tab: 'sql' | 'predicate') => void
}) {
  // Empty state: no analysis yet. Show one card with the "awaiting
  // triage" placeholder so the grid cell is still occupied.
  if (!triage || !preview) {
    return (
      <Card className="min-w-0">
        <CardHeader>
          <SectionTitle
            icon={<ShieldAlert />}
            title="Support verdict and exports"
            description="Can GBIF support this study, what to watch for, and the generated R / Python / SQL workflow."
          />
        </CardHeader>
        <CardContent>
          <EmptyState
            title="Awaiting triage"
            body="After you run the analysis, GBIF Workbench will classify your study as supported, conditional, exploratory, or unsupported, then surface risks and a one-click workflow export."
          />
        </CardContent>
      </Card>
    )
  }

  // Loaded state: one outer Card containing two sub-sections separated
  // by a thin divider. The divider doubles as a visible signal that
  // the Exports sub-section is loading (or has loaded) independently
  // of the Support verdict above.
  const hasExports = Boolean(workflow && query)

  return (
    <Card className="min-w-0" aria-label="Support verdict and exports">
      <CardHeader>
        <SectionTitle
          icon={<ShieldAlert />}
          title="Support verdict and exports"
          description="Can GBIF support this study, what to watch for, and the generated R / Python / SQL workflow."
        />
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Support verdict — fast, from /api/study-plan */}
        <section aria-label="Support verdict" className="space-y-6">
          <SupportPanel triage={triage} />
          <RiskPanel risks={triage.risks} />
        </section>

        {/* Thin divider so the user can see the visual join between the
            two sub-sections, and so the loading spinner below has a
            clear "this is the boundary" affordance. */}
        <div className="border-t border-border/60" aria-hidden="true" />

        {/* Exports — slow, from /api/workflow. Renders a skeleton
            spinner while the call is in flight and the full
            WorkflowPanel once it lands. */}
        <section aria-label="Exports" id="exports" className="space-y-4">
          <SectionTitle
            icon={<ShieldAlert />}
            title="Exports"
            description="R / Python / SQL / cleaning / writeup — built on the verdict above."
          />
          {hasExports ? (
            <WorkflowPanel
              workflow={workflow!}
              query={query!}
              triage={triage}
              activeGroup={activeWorkflowGroup}
              setActiveGroup={setActiveWorkflowGroup}
              activeCodeLanguage={activeCodeLanguage}
              setActiveCodeLanguage={setActiveCodeLanguage}
              activeWriteupTab={activeWriteupTab}
              setActiveWriteupTab={setActiveWriteupTab}
              activeQueryTab={activeQueryTab}
              setActiveQueryTab={setActiveQueryTab}
            />
          ) : (
            <WorkflowLoadingPanel error={workflowError} />
          )}
        </section>
      </CardContent>
    </Card>
  )
}